apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-argo
spec:
  project: nginx-demo
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  source:
    path: argo-examples
    repoURL: https://github.com/dwarakanathreddy/Kubernetes-RunBook.git
    targetRevision: main